### ISSUE TITLE
Data Folder

### ISSUE THREAD

**Issue by rafadsm** [TheOrestes/D3D9#1]
Hello, first of all I want to thank you for this wonderful project, although it was 7 years ago, I can learn a few things about DirectX9

If you still have files of the **Data** folder, could you share them? I would like to run the project and try to do something

My knowledge of dx9 is little and I would like to learn more about this project (although it is a very old graphical API, it works well)

I also have a question about the .scn file, was it done manually or exported by a program? 
If it was exported by a program, which program? 
I didn't find much about .scn

Thanks!

**Comment by TheOrestes** [comment]
Hi, If I remember correctly, the scn file was written manually & later simple parser was written to parse it.  I will need to search for that Data folder. I will mail you as soon as find it! Please note that every external library that's used in the code is way too old & would recommend to stick to the same version instead of latest one while trying to build.
